[project]
name = "mcp-crewai-workshop"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.102.0",
    "dotenv>=0.9.9",
    "mcp-run>=0.1.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
