greeting_task:
  description: >
    Generate a simple greeting message.
  expected_output: A friendly greeting.
  agent: assistant

story_task:
  description: >
    Write a short creative story about a fun day.
  expected_output: A brief, creative story using gemini 2.0 flash model.
  agent: writer
